#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

source /etc/network_turbo
source /root/miniconda3/etc/profile.d/conda.sh
conda activate opsd

MODEL_NAME_OR_PATH="${MODEL_NAME_OR_PATH:-/root/autodl-tmp/models/Qwen2.5-VL-3B-Instruct}"
DATASET_NAME="${DATASET_NAME:-${REPO_ROOT}/data/HaloQuest_vlm_local}"
TRAIN_SPLIT="${TRAIN_SPLIT:-train}"
PROBLEM_FIELD="${PROBLEM_FIELD:-question}"
SOLUTION_FIELD="${SOLUTION_FIELD:-solution}"
IMAGE_FIELD="${IMAGE_FIELD:-image}"

NUM_PROCESSES="${NUM_PROCESSES:-4}"
PER_DEVICE_BS="${PER_DEVICE_BS:-1}"
GRAD_ACCUM_STEPS="${GRAD_ACCUM_STEPS:-2}"
MAX_STEPS="${MAX_STEPS:-1000}"
MAX_LENGTH="${MAX_LENGTH:-16384}"
MAX_COMPLETION_LENGTH="${MAX_COMPLETION_LENGTH:-512}"

PERTURBATION_MODE="${PERTURBATION_MODE:-clean-noise}"
PAIR_SAMPLING_STRATEGY="${PAIR_SAMPLING_STRATEGY:-first}"
NOISE_STEPS="${NOISE_STEPS:-500}"
USE_TENSOR_DIFFUSION_NOISE="${USE_TENSOR_DIFFUSION_NOISE:-1}"

RUN_CONFIG="${RUN_CONFIG:-opsd_vcd_haloquest_4gpu_len16384_mc512_cleannoise_vcd_s1000}"
OUTPUT_DIR="${OUTPUT_DIR:-${REPO_ROOT}/output/opsd_haloquest_4gpu/${RUN_CONFIG}}"
WANDB_PROJECT="${WANDB_PROJECT:-OPSD-HaloQuest}"
REPORT_TO="${REPORT_TO:-wandb}"

MODEL_NAME_OR_PATH="${MODEL_NAME_OR_PATH}" \
DATASET_NAME="${DATASET_NAME}" \
TRAIN_SPLIT="${TRAIN_SPLIT}" \
PROBLEM_FIELD="${PROBLEM_FIELD}" \
SOLUTION_FIELD="${SOLUTION_FIELD}" \
IMAGE_FIELD="${IMAGE_FIELD}" \
NUM_PROCESSES="${NUM_PROCESSES}" \
PER_DEVICE_BS="${PER_DEVICE_BS}" \
GRAD_ACCUM_STEPS="${GRAD_ACCUM_STEPS}" \
MAX_STEPS="${MAX_STEPS}" \
MAX_LENGTH="${MAX_LENGTH}" \
MAX_COMPLETION_LENGTH="${MAX_COMPLETION_LENGTH}" \
PERTURBATION_MODE="${PERTURBATION_MODE}" \
PAIR_SAMPLING_STRATEGY="${PAIR_SAMPLING_STRATEGY}" \
NOISE_STEPS="${NOISE_STEPS}" \
USE_TENSOR_DIFFUSION_NOISE="${USE_TENSOR_DIFFUSION_NOISE}" \
RUN_CONFIG="${RUN_CONFIG}" \
OUTPUT_DIR="${OUTPUT_DIR}" \
WANDB_PROJECT="${WANDB_PROJECT}" \
REPORT_TO="${REPORT_TO}" \
bash "${REPO_ROOT}/scripts/run_opsd_vcd_debug_4gpu.sh"
