#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

MODEL_PATH="${MODEL_PATH:-/root/autodl-tmp/models/Qwen2.5-VL-3B-Instruct}"
PROCESSOR_PATH="${PROCESSOR_PATH:-${MODEL_PATH}}"

OUTPUT_ROOT="${OUTPUT_ROOT:-${REPO_ROOT}/output/eval_baseline_vcd_paper_$(date +%Y%m%d_%H%M%S)}"
PARALLEL_GPUS="${PARALLEL_GPUS:-4}"
GEN_PARALLEL_GPUS="${GEN_PARALLEL_GPUS:-${PARALLEL_GPUS}}"
BATCH_SIZE="${BATCH_SIZE:-4}"
GEN_BATCH_SIZE="${GEN_BATCH_SIZE:-4}"
TORCH_DTYPE="${TORCH_DTYPE:-float16}"
SEED="${SEED:-42}"

TEMPERATURE="${TEMPERATURE:-1.0}"
TOP_P="${TOP_P:-1.0}"
TOP_K="${TOP_K:-}"
POPE_MAX_NEW_TOKENS="${POPE_MAX_NEW_TOKENS:-20}"
YN_MAX_NEW_TOKENS="${YN_MAX_NEW_TOKENS:-20}"
MMHAL_MAX_NEW_TOKENS="${MMHAL_MAX_NEW_TOKENS:-128}"

VCD_ALPHA="${VCD_ALPHA:-1.0}"
VCD_BETA="${VCD_BETA:-0.1}"
VCD_GAMMA="${VCD_GAMMA:-0.1}"
VCD_NOISE_STEPS="${VCD_NOISE_STEPS:-500}"
VCD_VIEW_PAIR="${VCD_VIEW_PAIR:-clean-noise}"

RUN_JUDGE="${RUN_JUDGE:-1}"
JUDGE_MODEL="${JUDGE_MODEL:-gpt-4o}"
JUDGE_SLEEP_SEC="${JUDGE_SLEEP_SEC:-1.0}"
JUDGE_API_BASE="${JUDGE_API_BASE:-}"
JUDGE_API_KEY="${JUDGE_API_KEY:-}"

mkdir -p "${OUTPUT_ROOT}"

echo "[paper-vcd] MODEL_PATH=${MODEL_PATH}"
echo "[paper-vcd] OUTPUT_ROOT=${OUTPUT_ROOT}"
echo "[paper-vcd] TEMPERATURE=${TEMPERATURE}, TOP_P=${TOP_P}, TOP_K=${TOP_K:-<none>}"
echo "[paper-vcd] VCD alpha=${VCD_ALPHA}, beta=${VCD_BETA}, noise_steps=${VCD_NOISE_STEPS}, view_pair=${VCD_VIEW_PAIR}"

echo "[step] POPE baseline vs baseline+VCD"
BASELINE_MODEL_PATH="${MODEL_PATH}" \
OURS_MODEL_PATH="${MODEL_PATH}" \
OURS_BASE_MODEL_PATH="none" \
PROCESSOR_PATH="${PROCESSOR_PATH}" \
OUTPUT_ROOT="${OUTPUT_ROOT}/pope" \
TEMPERATURE="${TEMPERATURE}" \
TOP_P="${TOP_P}" \
TOP_K="${TOP_K}" \
MAX_NEW_TOKENS="${POPE_MAX_NEW_TOKENS}" \
SEED="${SEED}" \
TORCH_DTYPE="${TORCH_DTYPE}" \
GEN_BATCH_SIZE="${GEN_BATCH_SIZE}" \
GEN_PARALLEL_GPUS="${GEN_PARALLEL_GPUS}" \
BASELINE_USE_VCD_DECODING=0 \
OURS_USE_VCD_DECODING=1 \
OURS_VCD_ALPHA="${VCD_ALPHA}" \
OURS_VCD_BETA="${VCD_BETA}" \
OURS_VCD_GAMMA="${VCD_GAMMA}" \
OURS_VCD_NOISE_STEPS="${VCD_NOISE_STEPS}" \
OURS_VCD_VIEW_PAIR="${VCD_VIEW_PAIR}" \
bash "${REPO_ROOT}/scripts/run_pope_official_compare.sh"

echo "[step] HallusionBench baseline vs baseline+VCD"
BASELINE_MODEL_PATH="${MODEL_PATH}" \
OURS_MODEL_PATH="${MODEL_PATH}" \
OURS_BASE_MODEL_PATH="none" \
PROCESSOR_PATH="${PROCESSOR_PATH}" \
OUTPUT_ROOT="${OUTPUT_ROOT}/hallusionbench" \
BATCH_SIZE="${BATCH_SIZE}" \
PARALLEL_GPUS="${PARALLEL_GPUS}" \
TORCH_DTYPE="${TORCH_DTYPE}" \
TEMPERATURE="${TEMPERATURE}" \
TOP_P="${TOP_P}" \
TOP_K="${TOP_K}" \
MAX_NEW_TOKENS="${YN_MAX_NEW_TOKENS}" \
BASELINE_USE_VCD_DECODING=0 \
OURS_USE_VCD_DECODING=1 \
OURS_VCD_ALPHA="${VCD_ALPHA}" \
OURS_VCD_BETA="${VCD_BETA}" \
OURS_VCD_GAMMA="${VCD_GAMMA}" \
OURS_VCD_NOISE_STEPS="${VCD_NOISE_STEPS}" \
OURS_VCD_VIEW_PAIR="${VCD_VIEW_PAIR}" \
bash "${REPO_ROOT}/scripts/run_hallusionbench_compare.sh"

echo "[step] MME baseline vs baseline+VCD"
BASELINE_MODEL_PATH="${MODEL_PATH}" \
OURS_MODEL_PATH="${MODEL_PATH}" \
OURS_BASE_MODEL_PATH="none" \
PROCESSOR_PATH="${PROCESSOR_PATH}" \
OUTPUT_ROOT="${OUTPUT_ROOT}/mme" \
BATCH_SIZE="${BATCH_SIZE}" \
PARALLEL_GPUS="${PARALLEL_GPUS}" \
TORCH_DTYPE="${TORCH_DTYPE}" \
TEMPERATURE="${TEMPERATURE}" \
TOP_P="${TOP_P}" \
TOP_K="${TOP_K}" \
MAX_NEW_TOKENS="${YN_MAX_NEW_TOKENS}" \
BASELINE_USE_VCD_DECODING=0 \
OURS_USE_VCD_DECODING=1 \
OURS_VCD_ALPHA="${VCD_ALPHA}" \
OURS_VCD_BETA="${VCD_BETA}" \
OURS_VCD_GAMMA="${VCD_GAMMA}" \
OURS_VCD_NOISE_STEPS="${VCD_NOISE_STEPS}" \
OURS_VCD_VIEW_PAIR="${VCD_VIEW_PAIR}" \
bash "${REPO_ROOT}/scripts/run_mme_compare.sh"

echo "[step] MMHal baseline vs baseline+VCD"
BASELINE_MODEL_PATH="${MODEL_PATH}" \
OURS_MODEL_PATH="${MODEL_PATH}" \
OURS_BASE_MODEL_PATH="none" \
PROCESSOR_PATH="${PROCESSOR_PATH}" \
OUTPUT_ROOT="${OUTPUT_ROOT}/mmhal" \
BATCH_SIZE="${BATCH_SIZE}" \
PARALLEL_GPUS="${PARALLEL_GPUS}" \
TORCH_DTYPE="${TORCH_DTYPE}" \
TEMPERATURE="${TEMPERATURE}" \
TOP_P="${TOP_P}" \
TOP_K="${TOP_K}" \
MAX_NEW_TOKENS="${MMHAL_MAX_NEW_TOKENS}" \
RUN_JUDGE="${RUN_JUDGE}" \
JUDGE_MODEL="${JUDGE_MODEL}" \
JUDGE_SLEEP_SEC="${JUDGE_SLEEP_SEC}" \
JUDGE_API_BASE="${JUDGE_API_BASE}" \
JUDGE_API_KEY="${JUDGE_API_KEY}" \
BASELINE_USE_VCD_DECODING=0 \
OURS_USE_VCD_DECODING=1 \
OURS_VCD_ALPHA="${VCD_ALPHA}" \
OURS_VCD_BETA="${VCD_BETA}" \
OURS_VCD_GAMMA="${VCD_GAMMA}" \
OURS_VCD_NOISE_STEPS="${VCD_NOISE_STEPS}" \
OURS_VCD_VIEW_PAIR="${VCD_VIEW_PAIR}" \
bash "${REPO_ROOT}/scripts/run_mmhal_compare.sh"

echo "[done] baseline vs baseline+VCD paper-style outputs: ${OUTPUT_ROOT}"
