accelerate launch \
    --config_file accelerate.yaml \
    --num_processes 4 \
    --gradient_accumulation_steps 2 \
    --main_process_port 12949 \
    opsd_train.py \
    --model_name_or_path /data0/shared/Qwen3-1.7B \
    --learning_rate 5e-6 \
    --max_grad_norm 0.1 \
    --per_device_train_batch_size 4 \
    --gradient_checkpointing \
    --gradient_accumulation_steps 2 \
    --output_dir /data0/siyanz/opsd/ \
    --run_config qwen31b_prism_opsd \
    --num_train_epochs 30 \
    --max_completion_length 1024 \
    --save_steps 25 \
    --logging_steps 2 \
    --attn_implementation flash_attention_2 \
    --torch_dtype bfloat16 \
    --max_length 20000 \
    --beta 0 \
    --use_multimodal_processor \
    --use_peft \
    --lora_r 64 \
    --lora_alpha 128 \
    --lora_target_modules q_proj k_proj v_proj o_proj gate_proj up_proj down_proj \
    --temperature 1.1 \
    --top_p 0.95 \
    --top_k 20 \
    --lmbda 1 \
    --fixed_teacher \
    --jsd_token_clip 0.05 \
    --use_vcd_opsd \
    --vcd_alpha 1.0 \
    --view_pairs clean-noise,mask-clean \
    --view_field_prefix problem_ \
    --pair_sampling_strategy random \
    --use_image_perturbation_pairs \
    --image_field image \
    --image_token "<image>" \
    --noise_std 25.0 \
    --mask_ratio 0.25 \
    --blur_radius 2.0 \
    --use_privileged_visual_teacher \
    --privileged_visual_field privileged_visual_evidence \
    --good_view_field problem_good_view \
    --bad_view_field problem_bad_view \
    --wandb_project OPSD
